# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: v1.1.3
_src_path: https://github.com/radioconda/gnuradio-oot-recipe-template
description: "This GNU Radio module is developed to realize signal analysis abilities\n\
    in typical block-structure. The module is capable of the following:\n\n    Energy\
    \ detection of continuous signals\n    Filtering of detected signals\n    OFDM\
    \ parameter estimation (carrier spacing, symbol time)\n    Blind OFDM synchronization\n\
    \    Resampling of signals to constant rate"
example_flowgraphs: ofdm_estimation
git_branch: main
git_url: https://github.com/gnuradio/gr-inspector.git
grc_blocks: 'ofdm_synchronizer_cc

    ofdm_zkf_c

    qtgui_inspector_sink_vf

    signal_detector_cvf

    signal_extractor_c

    signal_separator_c'
installs_examples: true
installs_grc_blocks: true
license: GPL-3.0-or-later
license_file: LICENSE
maintainer_username: ryanvolz
oot_name: inspector
python_only: false
summary: GNU Radio signal analysis toolbox
