# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json
context:
  oot_name: howto
  name: gnuradio-${{ oot_name }}
  # update script relies on `git_url` and `git_branch` and can replace:
  #   `git_rev`, `base_version`, `date_str`, `build`
  git_url: https://github.com/radioconda/gr-howto.git
  git_branch: main
  git_rev: e6c8b2997371830cce03c0a8a05b6f0526b4efa4
  base_version: "0.0.0"
  date_str: "20250101"
  version: ${{ base_version }}.post${{ date_str }}+g${{ git_rev[:7] }}
  build: "0"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  git: ${{ git_url }}
  rev: ${{ git_rev }}

build:
  number: ${{ build }}
  files:
    exclude:
      - "**/gdk-pixbuf*"
      - "**/*.pyc"

requirements:
  build:
    - if: build_platform != target_platform
      then:
        - python
        - cross-python_${{ target_platform }}
        - numpy
        - pybind11
    - ${{ compiler("c") }}
    - ${{ stdlib("c") }}
    - ${{ compiler("cxx") }}
    - cmake
    - git
    - ninja
    - pkg-config
  host:
    - gnuradio-core
    - libboost-devel
    - numpy
    - if: win
      then: pip
    - pybind11
    - python
    - volk
  run:
    - numpy
    - python
  ignore_run_exports:
    from_package:
      # this only builds against the headers
      - libboost-devel

tests:
  - python:
      imports:
        - gnuradio.${{ oot_name }}
      pip_check: false
  - package_contents:
      include:
        - gnuradio/${{ oot_name }}/api.h
      lib:
        - ${{ name }}
      files:
        # Example flowgraphs
#        - ${{ "Library/" if win }}share/gnuradio/examples/${{ oot_name }}/howto.grc

        # GRC blocks
#        - ${{ "Library/" if win }}share/gnuradio/grc/blocks/${{ oot_name }}_example.block.yml
  - script:
      # Verify that example flowgraphs can be generated
#      - if: unix
#        then: |
#          grcc $PREFIX/share/gnuradio/examples/${{ oot_name }}/howto.grc
#      - if: win
#        then: |
#          grcc %PREFIX%\\Library\\share\\gnuradio\\examples\\${{ oot_name }}\\howto.grc

      # Verify that commands run
#      - COMMAND --help
    requirements:
      run:
#        - gnuradio-grc

about:
#  homepage: https://github.com/radioconda/gr-howto
#  license: GPL-3.0-or-later
#  license_file: LICENSE
#  summary: GNU Radio howto module
#  description: >
#    Short description of the gr-howto module.
#
#    Example gnuradio-companion flowgraphs are installed with the package and
#    can be found in:
#        - (Linux/macOS) `$CONDA_PREFIX/share/gnuradio/examples/${{ oot_name }}`
#        - (Windows) `%CONDA_PREFIX%\share\gnuradio\examples\${{ oot_name }}`

extra:
  recipe-maintainers:
#    - ryanvolz
