# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/pixi/refs/heads/main/schema/schema.json

[project]
authors = ["Ryan Volz <ryan.volz@gmail.com>"]
channels = ["conda-forge"]
description = "Conda recipes for GNU Radio Out-Of-Tree modules"
name = "gnuradio-oot-forge"
platforms = ["linux-64", "linux-aarch64", "linux-ppc64le", "osx-64", "osx-arm64", "win-64"]
version = "0.1.0"

[dependencies]
rattler-build = ">=0.47.0,<0.48"

[tasks.build]
cmd = [
    "rattler-build",
    "build",
    "--experimental",
    # HACK: workaround lack of ordering in building directory of recipes,
    # any recipe specified directly is built first so do gnuradio-foo first
    "--recipe=recipes/foo/recipe.yaml",
    "--recipe-dir=recipes",
    "--channel=https://prefix.dev/conda-forge",
    "--channel=https://prefix.dev/gnuradio-oot-forge",
]
inputs = ["recipes/**/*"]
outputs = ["output/**/*.conda", "output/**/repodata.json"]

[tasks.clean]
cmd = ["rm", "-rf", "output/bld", "output/src_cache"]

[feature.lint.dependencies]
actionlint = ">=1.7.7,<2"
pre-commit = ">=4.1.0,<5"
pre-commit-hooks = ">=5.0.0,<6"
ruff = ">=0.9.7,<0.10"

[feature.lint.tasks]
actionlint = { cmd = "actionlint", env = { SHELLCHECK_OPTS = "-e SC2086" } }
lint = "pre-commit run --all-files --hook-stage=manual"
pre-commit-install = "pre-commit install --install-hooks"
pre-commit-run = "pre-commit run --all-files"
ruff-format = "ruff format --force-exclude"
ruff-lint = "ruff check --fix --exit-non-zero-on-fix --force-exclude"

[feature.recipe.dependencies]
python = ">=3.11"
pyyaml = "*"
rich = ">=13.9.4,<14"

[feature.render-variants.dependencies]
conda-forge-pinning = "*"

[feature.render-variants.tasks]
render-variants = "python .scripts/render-variants.py"

[feature.template.dependencies]
copier = ">=9.6.0,<10"
ipython = ">=9.2.0,<10"
license-expression = ">=30.4.1,<31"

[feature.template.tasks]
generate = "python .scripts/generate-from-template.py"
update-from-template = "python .scripts/update-from-template.py"

[feature.update-versions.dependencies]
gitpython = "*"
setuptools_scm = "*"

[feature.update-versions.tasks]
update-versions = "python .scripts/update-versions.py"

[environments]
lint = {features = ["lint"], no-default-feature=true}
render-variants = ["recipe", "render-variants"]
update-versions = {features = ["recipe", "update-versions"], no-default-feature=true}
template = {features = ["recipe", "update-versions", "template"], no-default-feature=true}
