# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/pixi/refs/heads/main/schema/schema.json

[project]
authors = ["Ryan Volz <ryan.volz@gmail.com>"]
channels = ["conda-forge"]
description = "Conda recipes for GNU Radio Out-Of-Tree modules"
name = "gnuradio-oot-forge"
platforms = ["linux-64", "linux-aarch64", "osx-64", "osx-arm64", "win-64"]
version = "0.1.0"

[dependencies]
rattler-build = ">=0.36.0,<0.37"

[feature.recipe.dependencies]
python = ">=3.11"
pyyaml = "*"

[feature.conda-forge-pinning.dependencies]
conda-forge-pinning = "*"

[feature.conda-forge-pinning.tasks]
render-variants = "python .scripts/render-variants.py"

[feature.update-versions.dependencies]
requests = "*"

[feature.update-versions.tasks]
update-versions = "python .scripts/update-versions.py"

[environments]
render-variants = ["recipe", "conda-forge-pinning"]
update-versions = ["recipe", "update-versions"]

[tasks.build]
cmd = [
    "rattler-build",
    "build",
    "--experimental",
    "--recipe-dir=recipes",
    "--channel=https://prefix.dev/conda-forge",
    "--channel=https://prefix.dev/gnuradio-oot-forge",
]
inputs = ["recipes/**/*"]
outputs = ["output/**/*.conda", "output/**/repodata.json"]

[tasks.clean]
cmd = ["rm", "-rf", "output/bld", "output/src_cache"]
