# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/pixi/refs/heads/main/schema/schema.json

[project]
authors = ["Ryan Volz <ryan.volz@gmail.com>"]
channels = ["conda-forge"]
description = "Conda recipes for GNU Radio Out-Of-Tree modules"
name = "gnuradio-oot-forge"
platforms = ["linux-64", "linux-aarch64", "osx-64", "osx-arm64", "win-64"]
version = "0.1.0"

[dependencies]
rattler-build = ">=0.36.0,<0.37"
conda-forge-pinning = ">=2025.2.18.15.16.45,<2026"

[feature.update-versions.dependencies]
python = "*"
requests = "*"
pyyaml = "*"

[feature.update-versions.tasks]
update-versions = "python .scripts/update-versions.py"

[environments]
update-versions = ["update-versions"]

[tasks.build]
cmd = [
    "rattler-build",
    "build",
    "--experimental",
    "--recipe-dir=recipes",
    "--channel=https://prefix.dev/conda-forge",
    "--channel=https://prefix.dev/gnuradio-oot-forge",
    "--variant-config=$CONDA_PREFIX/conda_build_config.yaml",
    "--variant-config=recipes/variants.yaml",
]
inputs = ["recipes/**/*"]
outputs = ["output/**/*.conda", "output/**/repodata.json"]

[tasks.clean]
cmd = ["rm", "-rf", "output/bld", "output/src_cache"]
