# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: v1.1.3
_src_path: https://github.com/radioconda/gnuradio-oot-recipe-template
description: 'Gr-leo is a GNU Radio Out-of-Tree module that simulates the

    telecommunication channel between orbiting satellites and Ground Stations.'
example_flowgraphs: leo_channel
git_branch: master
git_url: https://gitlab.com/librespacefoundation/gr-leo.git
grc_blocks: 'leo_channel_model

    variable_antenna

    variable_leo_model_def

    variable_satellite

    variable_tracker'
installs_examples: true
installs_grc_blocks: true
license: GPL-3.0-or-later AND Apache-2.0
license_file: LICENSE
maintainer_username: ryanvolz
oot_name: leo
python_only: false
summary: A GNU Radio space telecommunication simulator
