# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json
context:
  oot_name: leo
  name: gnuradio-${{ oot_name }}
  # update script relies on `git_url` and `git_branch` and can replace:
  #   `git_rev`, `base_version`, `date_str`, `build`
  git_url: https://github.com/radioconda/gr-leo.git
  git_branch: updates
  git_rev: 8f62b92dd2fed042610e810b1c41ea7f6978262f
  base_version: "1.0.0"
  date_str: "20250214"
  version: ${{ base_version }}.post${{ date_str }}+g${{ git_rev[:7] }}
  build: "3"

recipe:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  - git: ${{ git_url }}
    rev: ${{ git_rev }}
  - git: https://github.com/dnwrnr/sgp4.git
    rev: 147b1ae7cfbd5608ba78f4af29f6ba8e364e3b1b  # v1.0.post7
    target_directory: sgp4

outputs:
  - package:
      name: ${{ name|lower }}-data
    build:
      number: ${{ build }}
      string: ${{ "win" if win else "unix" }}_${{ build }}
      noarch: generic
      script:
        interpreter: python
        content: |
          import os
          import pathlib
          import shutil

          src_dirs = pathlib.Path("data").glob("ITU_RREC*")
          dest_dir = pathlib.Path(os.environ["PREFIX"]) / "${{ "Library/" if win }}share/gr-leo"

          dest_dir.mkdir(parents=True, exist_ok=True)
          for src_dir in src_dirs:
              shutil.copytree(src_dir, dest_dir / src_dir.name)
    requirements:
      build:
        - python
      run:
        - if: unix
          then: __unix
        - if: win
          then: __win
    tests:
      - package_contents:
          files:
            - ${{ "Library/" if win }}share/gr-leo/ITU_RREC_P1511/TOPOLAT.txt
            - ${{ "Library/" if win }}share/gr-leo/ITU_RREC_P837/LAT_R001.TXT
            - ${{ "Library/" if win }}share/gr-leo/ITU_RREC_P839/Lat.txt

  - package:
      name: ${{ name|lower }}
    build:
      number: ${{ build }}
      script:
        file: build
      files:
        exclude:
          - "**/gdk-pixbuf*"
          - "**/*.pyc"
          - ${{ "Library/" if win }}share/gr-leo/ITU_RREC*
    requirements:
      build:
        - if: build_platform != target_platform
          then:
            - python
            - cross-python_${{ target_platform }}
            - numpy
            - pybind11
        - ${{ compiler("c") }}
        - ${{ stdlib("c") }}
        - ${{ compiler("cxx") }}
        - cmake
        - git
        - ninja
        - pkg-config
      host:
        - gnuradio-core
        - libboost-devel
        - numpy
        - if: win
          then: pip
        - pybind11
        - python
        - volk
      run:
        - ${{ pin_subpackage('gnuradio-leo-data', exact=True) }}
        - numpy
        - python
      ignore_run_exports:
        from_package:
          # this only builds against the headers
          - libboost-devel
    tests:
      - python:
          imports:
            - gnuradio.${{ oot_name }}
          pip_check: false
      - package_contents:
          include:
            - gnuradio/${{ oot_name }}/api.h
          lib:
            - ${{ name }}
          files:
            - ${{ "Library/" if win }}share/gnuradio/grc/blocks/leo_channel_model.block.yml
            - ${{ "Library/" if win }}share/gnuradio/grc/blocks/variable_antenna.block.yml
            - ${{ "Library/" if win }}share/gnuradio/grc/blocks/variable_leo_model_def.block.yml
            - ${{ "Library/" if win }}share/gnuradio/grc/blocks/variable_satellite.block.yml
            - ${{ "Library/" if win }}share/gnuradio/grc/blocks/variable_tracker.block.yml
      #- script:
          #- if: unix
            #then: |
              #leo_passpredict.py --help
              #grcc $PREFIX/share/gnuradio/examples/leo/leo_channel.grc
          #- if: win
            #then: |
              #leo_passpredict --help
              #grcc %PREFIX%\\Library\\share\\gnuradio\\examples\\leo\\leo_channel.grc
        #requirements:
          #run:
            #- gnuradio-grc
            #- gnuradio-qtgui
            #- python

about:
  homepage: https://gitlab.com/librespacefoundation/gr-leo
  license: GPL-3.0-or-later AND Apache-2.0
  license_file:
    - LICENSE
    - sgp4/LICENSE
  summary: A GNU Radio space telecommunication simulator
  description: >
    Gr-leo is a GNU Radio Out-of-Tree module that simulates the
    telecommunication channel between orbiting satellites and Ground Stations.

    Example gnuradio-companion flowgraphs are installed with the package and
    can be found in:
        - (Linux/macOS) `$CONDA_PREFIX/share/gnuradio/examples/leo`
        - (Windows) `%CONDA_PREFIX%\share\gnuradio\examples\leo`

extra:
  recipe-maintainers:
    - ryanvolz
