# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: v1.1.3
_src_path: https://github.com/radioconda/gnuradio-oot-recipe-template
description: 'The goal of this project is to build a software-defined OFDM transmitter

    that "paints" monochrome images into the waterfall of a receiver.

    It is based on https://github.com/polygon/spectrum_painter.


    After installation, a GNU Radio block called "Spectrum Painter" will

    be available in the "Paint" category. The block converts a byte stream

    of image data into a 4K IFFT OFDM IQ sequence for transmission.'
git_branch: master
git_url: https://github.com/drmpeg/gr-paint.git
grc_blocks: 'image_source

    paint_bc'
installs_examples: false
installs_grc_blocks: true
license: GPL-3.0-or-later
license_file: COPYING
maintainer_username: ryanvolz
oot_name: paint
python_only: false
summary: GNU Radio module for OFDM spectrum painting
