# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: v1.1.3
_src_path: https://github.com/radioconda/gnuradio-oot-recipe-template
description: This is an IEEE802.15.4 O-QPSK transceiver for GNU Radio, based on Thomas
    Schmid's implementation.
example_flowgraphs: 'ieee802_15_4_CSS_PHY

    ieee802_15_4_OQPSK_PHY

    transceiver_CSS_loopback

    transceiver_CSS_USRP

    transceiver_OQPSK'
git_branch: maint-3.10
git_url: https://github.com/bastibl/gr-ieee802-15-4.git
grc_blocks: 'access_code_prefixer

    access_code_removal_b

    chips_to_bits_fb

    codeword_demapper_ib

    codeword_mapper_bi

    deinterleaver_ff

    dqcsk_demapper_cc

    dqcsk_mapper_fc

    dqpsk_mapper_ff

    dqpsk_soft_demapper_cc

    frame_buffer_cc

    interleaver_ii

    mac

    multiuser_chirp_detector_cc

    packet_sink

    phr_prefixer

    phr_removal

    preamble_sfd_prefixer_ii

    preamble_tagger_cc

    qpsk_demapper_fi

    qpsk_mapper_if

    rime_stack

    zeropadding_b

    zeropadding_removal_b'
installs_examples: true
installs_grc_blocks: true
license: GPL-3.0-or-later
license_file: LICENSE
maintainer_username: ryanvolz
oot_name: ieee802_15_4
python_only: false
summary: IEEE 802.15.4 ZigBee Transceiver for GNU Radio
