# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: v1.1.3
_src_path: https://github.com/radioconda/gnuradio-oot-recipe-template
description: 'The gr-radar project provides a toolbox of commonly used radar algorithms.

    An important part is the UHD Echotimer, which enables a synchronized TX and

    RX stream from USRPs to ensure a constant phase relation in measurements.

    Example flowgraphs for CW, Dual CW, FSK, FMCW and OFDM radar are given and

    partly tested on hardware. GUI elements for target representation and

    further signal processing algorithms such as target tracking are

    implemented. Check out the project website for example videos and further

    information.'
example_flowgraphs: simulator_cw
git_branch: master
git_url: https://github.com/kit-cel/gr-radar.git
grc_blocks: 'crop_matrix_vcvc

    estimator_cw

    find_max_peak_c

    msg_gate

    ofdm_cyclic_prefix_remover_cvc

    os_cfar_2d_vc

    print_results

    qtgui_scatter_plot

    signal_generator_cw_c

    split_cc

    static_target_simulator_cc

    tracking_singletarget

    transpose_matrix_vcvc

    trigger_command

    ts_fft_cc

    usrp_echotimer_cc'
installs_examples: true
installs_grc_blocks: true
license: GPL-3.0-or-later
license_file: LICENSE
maintainer_username: ryanvolz
oot_name: radar
python_only: false
summary: GNU Radio Radar Toolbox
