# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: v1.1.3
_src_path: https://github.com/radioconda/gnuradio-oot-recipe-template
description: "This is a collection of custom blocks that are not directly associated\
    \ with\na project. For sample applications see:\n\n    * https://github.com/bastibl/gr-ieee802-11\n\
    \    * https://github.com/bastibl/gr-ieee802-15-4"
git_branch: maint-3.10
git_url: https://github.com/bastibl/gr-foo.git
grc_blocks: 'burst_tagger

    channel_model

    packet_dropper

    packet_pad2

    pad_tagged_stream

    periodic_msg_source

    random_periodic_msg_source

    rtt_measure

    selector

    valve

    wireshark_connector'
installs_examples: false
installs_grc_blocks: true
license: GPL-3.0-or-later
license_file: LICENSE
maintainer_username: ryanvolz
oot_name: foo
python_only: false
summary: Collection of GNU Radio blocks useful to other modules
