# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: v1.1.3
_src_path: https://github.com/radioconda/gnuradio-oot-recipe-template
description: 'A Radio Data System - Traffic Message Channel (RDS-TMC) module for GNU

    Radio. RDS is a communications protocol standard for embedding small

    amounts of digital information in conventional FM radio broadcasts.'
example_flowgraphs: 'rds_rx

    rds_tx'
git_branch: maint-3.10
git_url: https://github.com/bastibl/gr-rds.git
grc_blocks: 'decoder

    encoder

    panel

    parser'
installs_examples: true
installs_grc_blocks: true
license: GPL-3.0-or-later
license_file: COPYING
maintainer_username: ryanvolz
oot_name: rds
python_only: false
summary: GNU Radio module for an FM RDS/TMC Transceiver
