# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: v1.1.3
_src_path: https://github.com/radioconda/gnuradio-oot-recipe-template
description: 'GNU Radio modules for Hermes Lite 2.


    hermesNB sources decimated downconverted 48K-to-384K receiver complex

    stream(s), and sinks one 48k sample rate transmit complex stream.

    hermesWB sources raw ADC samples as a vector of floats, with vlen=16384.

    Each individual vector contains time contiguous samples. However there are

    large time gaps between between vectors. This is how HPSDR produces raw

    samples, it is due to Ethernet interface rate limitations between HPSDR and

    the host computer.'
example_flowgraphs: receive
git_branch: main
git_url: https://github.com/daniestevez/gr-hermeslite2.git
grc_blocks: 'NB

    WB'
installs_examples: true
installs_grc_blocks: true
license: GPL-3.0-or-later
license_file: LICENSE
maintainer_username: ryanvolz
oot_name: hermeslite2
python_only: false
summary: GNU Radio interface module for Hermes Lite 2
