# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: v1.1.2
_src_path: /home/rvolz/repos/gnuradio-oot-recipe-template/
description: 'A GNU Radio out-of-tree (OOT) module to demodulate and decode Automatic

    Dependent Surveillance Broadcast (ADS-B) messages.


    To use the built-in web app, run `python -m gnuradio.adsb.webserver` and

    open a browser to http://127.0.0.1:5000.'
example_flowgraphs: adsb_rx
git_branch: maint-3.10
git_url: https://github.com/mhostetter/gr-adsb.git
grc_blocks: 'decoder

    demod

    framer'
installs_examples: true
installs_grc_blocks: true
license: GPL-3.0-or-later
license_file: COPYING
maintainer_username: ryanvolz
oot_name: adsb
python_only: true
summary: GNU Radio OOT module to demodulate and decode ADS-B messages
