# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: v1.1.3
_src_path: https://github.com/radioconda/gnuradio-oot-recipe-template
description: 'This an IEEE 802.11 a/g/p transceiver for GNU Radio that is fitted for

    operation with Ettus N210s and B210s. Interoperability was tested with many

    off-the-shelf WiFi cards and IEEE 802.11p prototypes. The code can also be

    used in simulations.'
example_flowgraphs: 'wifi_loopback

    wifi_phy_hier

    wifi_rx

    wifi_transceiver

    wifi_tx'
git_branch: maint-3.10
git_url: https://github.com/bastibl/gr-ieee802-11.git
grc_blocks: 'chunks_to_symbols

    decode_mac

    ether_encap

    extract_csi

    frame_equalizer

    mac

    mapper

    parse_mac

    sync_long

    sync_short'
installs_examples: true
installs_grc_blocks: true
license: GPL-3.0-or-later
license_file: LICENSE
maintainer_username: ryanvolz
oot_name: ieee802_11
python_only: false
summary: IEEE 802.11 a/g/p Transceiver for GNU Radio
