# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json
context:
  oot_name: ieee802_11
  name: gnuradio-ieee802_11
  # update script relies on `git_url` and `git_branch` and can replace:
  #   `git_rev`, `base_version`, `date_str`, `build`
  git_url: https://github.com/radioconda/gr-ieee802-11.git
  git_branch: updates
  git_rev: bf25796892c0e8ed624512de486a7ed5fd3d320e
  base_version: "0.0.0"
  date_str: "20250915"
  version: ${{ base_version }}.${{ date_str }}.dev+g${{ git_rev[:7] }}
  build: "0"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  git: ${{ git_url }}
  rev: ${{ git_rev }}

build:
  number: ${{ build }}
  files:
    exclude:
      - "**/gdk-pixbuf*"
      - "**/*.pyc"

requirements:
  build:
    - if: build_platform != target_platform
      then:
        - python
        - cross-python_${{ target_platform }}
        - numpy
        - pybind11
    - ${{ compiler("c") }}
    - ${{ stdlib("c") }}
    - ${{ compiler("cxx") }}
    - cmake
    - git
    - ninja
    - pkg-config
  host:
    - fmt
    - gnuradio-core
    - libboost-devel
    - numpy
    - if: win
      then: pip
    - pybind11
    - python
    - spdlog
    - volk
  run:
    - gnuradio-foo
    - numpy
    - pyopengl
    - python
  ignore_run_exports:
    from_package:
      # this only builds against the headers
      - libboost-devel

tests:
  - python:
      imports:
        - ieee802_11
      pip_check: false
  - package_contents:
      include:
        - ieee802_11/api.h
      lib:
        - gnuradio-ieee802_11
      files:
        # Example flowgraphs
        - ${{ "Library/" if win }}share/gnuradio/examples/ieee802_11/wifi_loopback.grc
        - ${{ "Library/" if win }}share/gnuradio/examples/ieee802_11/wifi_phy_hier.grc
        - ${{ "Library/" if win }}share/gnuradio/examples/ieee802_11/wifi_rx.grc
        - ${{ "Library/" if win }}share/gnuradio/examples/ieee802_11/wifi_transceiver.grc
        - ${{ "Library/" if win }}share/gnuradio/examples/ieee802_11/wifi_tx.grc
        # GRC blocks
        - ${{ "Library/" if win }}share/gnuradio/grc/blocks/ieee802_11_chunks_to_symbols.block.yml
        - ${{ "Library/" if win }}share/gnuradio/grc/blocks/ieee802_11_decode_mac.block.yml
        - ${{ "Library/" if win }}share/gnuradio/grc/blocks/ieee802_11_ether_encap.block.yml
        - ${{ "Library/" if win }}share/gnuradio/grc/blocks/ieee802_11_extract_csi.block.yml
        - ${{ "Library/" if win }}share/gnuradio/grc/blocks/ieee802_11_frame_equalizer.block.yml
        - ${{ "Library/" if win }}share/gnuradio/grc/blocks/ieee802_11_mac.block.yml
        - ${{ "Library/" if win }}share/gnuradio/grc/blocks/ieee802_11_mapper.block.yml
        - ${{ "Library/" if win }}share/gnuradio/grc/blocks/ieee802_11_parse_mac.block.yml
        - ${{ "Library/" if win }}share/gnuradio/grc/blocks/ieee802_11_sync_long.block.yml
        - ${{ "Library/" if win }}share/gnuradio/grc/blocks/ieee802_11_sync_short.block.yml
  #- script:
      #- if: unix
        #then: |
          ## Put commands that test the package on Linux or macOS below
          ## Verify that example flowgraphs can be generated
          #grcc $PREFIX/share/gnuradio/examples/ieee802_11/wifi_phy_hier.grc
          #grcc $PREFIX/share/gnuradio/examples/ieee802_11/wifi_rx.grc
      #- if: win
        #then: |
          #:: Put commands that test the package on Windows below
          #:: Verify that example flowgraphs can be generated
          #grcc %PREFIX%\\Library\\share\\gnuradio\\examples\\ieee802_11\\wifi_phy_hier.grc
          #grcc %PREFIX%\\Library\\share\\gnuradio\\examples\\ieee802_11\\wifi_rx.grc
    #requirements:
      #run:
        #- gnuradio-grc
        #- gnuradio-qtgui
        #- gnuradio-uhd

about:
  homepage: https://github.com/bastibl/gr-ieee802-11
  license: GPL-3.0-or-later
  license_file: LICENSE
  summary: IEEE 802.11 a/g/p Transceiver for GNU Radio
  description: >
    This an IEEE 802.11 a/g/p transceiver for GNU Radio that is fitted for
    operation with Ettus N210s and B210s. Interoperability was tested with many
    off-the-shelf WiFi cards and IEEE 802.11p prototypes. The code can also be
    used in simulations.

    Example gnuradio-companion flowgraphs are installed with the package and
    can be found in:
        - (Linux/macOS) `$CONDA_PREFIX/share/gnuradio/examples/ieee802_11`
        - (Windows) `%CONDA_PREFIX%\share\gnuradio\examples\ieee802_11`

extra:
  recipe-maintainers:
    - ryanvolz
