name: Update lockfiles and pinned variants

on:
  workflow_dispatch:
  schedule:
    - cron: 0 5 * * *

jobs:
  update-pins:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/create-github-app-token@v2
        id: generate-token
        with:
          app-id: ${{ secrets.RADIOCONDA_PRBOT_APP_ID }}
          private-key: ${{ secrets.RADIOCONDA_PRBOT_PRIVATE_KEY }}

      - uses: actions/checkout@v5

      - uses: prefix-dev/setup-pixi@v0.9.1
        with:
          run-install: false

      - name: Update lockfiles
        run: |
          set -o pipefail
          pixi update --json | pixi exec pixi-diff-to-markdown >> body.md

      - name: Update pinned variants
        run: |
          pixi run --environment render-variants render-variants --bump-build --summary-output body.md

      - name: Check for changed variants
        uses: tj-actions/verify-changed-files@v20
        id: verify-changed-files
        with:
          files: |
            recipes/**/variants.yaml

      - name: Create pull request
        uses: peter-evans/create-pull-request@v7
        if: steps.verify-changed-files.outputs.files_changed == 'true'
        with:
          token: ${{ steps.generate-token.outputs.token }}
          commit-message: Update pixi lockfile and pinned variants
          title: Update pixi lockfile and pinned variants
          body-path: body.md
          branch: update-pins
          base: main
          labels: pixi, pins
          delete-branch: true
          add-paths: |
            pixi.lock
            recipes/**/recipe.yaml
            recipes/**/variants.yaml
